language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - dledesma@fi.uba.ar
      - rocioarrua95@gmail.com
      - alberto.sayos.daniel@gmail.com
    on_failure: always
